name: "setup-uv-env"
description: "Composite action to setup the Python and uv environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      run: pip install uv
      shell: bash

    - name: Load cached uv venv
      id: cached-uv-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: uv-venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('pyproject.toml', 'requirements.txt') }}

    - name: Install dependencies
      if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
      run: uv sync
      shell: bash
