name: "setup-uv-env"
description: "Composite action to setup the Python and uv environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.14"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      run: uv sync --frozen
      shell: bash
